# Generated by Django 4.2.9 on 2024-02-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="branches",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="hospital",
            name="level",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="location",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
