# Generated by Django 4.2.9 on 2024-02-15 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "referral",
            "0002_hospital_branches_hospital_capacity_hospital_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="admission_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default=None,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="location",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.IntegerField(default=None),
        ),
    ]
