# Generated by Django 4.2.9 on 2024-02-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0003_patient_admission_date_patient_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
