# Generated by Django 4.2.9 on 2024-02-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0004_patient_first_name_patient_last_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="user",),
    ]
