# Generated by Django 4.2.9 on 2024-02-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0006_patient_id_number_patient_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="user",),
    ]
