# Generated by Django 4.2.9 on 2024-02-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0007_remove_patient_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="referral", name="referred_to_doctor",),
        migrations.AddField(
            model_name="referral",
            name="referred_to_hospital",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_received",
                to="referral.hospital",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referring_hospital",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_sent",
                to="referral.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="referring_doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="referral.doctor"
            ),
        ),
    ]
