# Generated by Django 4.2.9 on 2024-02-16 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referral", "0008_remove_referral_referred_to_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="referral", name="referring_doctor",),
        migrations.AddField(
            model_name="hospital",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Doctor",),
    ]
