# Generated by Django 4.2.9 on 2024-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0009_remove_referral_referring_doctor_hospital_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="email",
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
