# Generated by Django 4.2.9 on 2024-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0011_disease_hospital_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="password",
            field=models.CharField(default=1024, max_length=30),
        ),
    ]
