# Generated by Django 4.2.9 on 2024-02-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0012_alter_hospital_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="diseases",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="referral.disease",
            ),
        ),
    ]
