# Generated by Django 4.2.9 on 2024-02-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0014_remove_hospital_user_hospital_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(default="unknown", max_length=50),
        ),
    ]
